---
apiVersion: automationhub.ansible.com/v1beta1
kind: AutomationHub
metadata:
  name: automationhub-file-dev
  namespace: aap-ansible-poc
spec:
  route_tls_termination_mechanism: Edge
  ingress_type: Route
  loadbalancer_port: 80
  file_storage_size: 20Gi
  file_storage_storage_class: automationhub-sc-dev
  file_storage_access_mode: ReadWriteMany
  image_pull_policy: IfNotPresent
  # object_storage_s3_secret: s3-secret-automationhub-dev
  web:
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 1Gi
  content:
    log_level: INFO
    replicas: 2
    resource_requirements:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 4Gi
  postgres_storage_requirements:
    requests:
      storage: 20Gi
  api:
    log_level: INFO
    replicas: 1
    resource_requirements:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 300m
        memory: 1Gi
  postgres_resource_requirements:
    limits:
      cpu: '0'
      memory: '0'
    requests:
      cpu: '0'
      memory: '0'
  redis_resource_requirements:
    limits:
      cpu: '300m'
      memory: '1Gi'
    requests:
      cpu: '100m'
      memory: '512Mi'
  loadbalancer_protocol: http
  resource_manager:
    replicas: 1
    resource_requirements:
      limits:
        cpu: '300m'
        memory: '1Gi'
      requests:
        cpu: '100m'
        memory: '512Mi'
  # route_host: automationhub-dev.apps.cluster-7987.sandbox19.opentlc.com
  # storage_type: S3
  storage_type: File
  worker:
    replicas: 2
    resource_requirements:
      limits:
        cpu: '300m'
        memory: '1Gi'
      requests:
        cpu: '100m'
        memory: '512Mi'
...
