---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- ansible-automation-platform-og.yaml
- ansible-automation-platform-operator-sub.yaml
- ansible-automation-platform-ns.yaml
...  
