---
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationControllerRestore
metadata:
  name: example-restore
  namespace: aap-ansible-pro
spec:
  deployment_name: controller-pro-restore
  backup_pvc_namespace: aap-ansible-pro
  backup_source: Backup CR
  backup_name: example-backup-pro
...  
