---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- auto-controller-automationcontroller.yaml
- auto-controller-automationcontroller-backup-configmap.yaml
- auto-controller-automationcontroller-backup.yaml
- auto-controller-automationcontroller-backup-cronjob.yaml        
...  
